name: Continuous Integration

on:
  push:
    branches: [main]
  pull_request:

permissions:
  contents: write
  deployments: write
  id-token: write

jobs:
  continuous-integration:
    uses: adjust/githubWorkflows/.github/workflows/automatePackageCI.yml@v11.0.2
    with:
      python_version: 3.12
    secrets:
      SLACK_WEBHOOK_URL: ${{ secrets.AUTOMATE_SLACK_WEBHOOK }}
      GITHUB_ORGANIZATION_ACCESS_TOKEN: ${{ secrets.AUTOMATE_GITHUB_ACCESS_TOKEN }}
      GH_APP_PRIVATE_KEY: ${{ secrets.AUTOMATE_GITHUB_APP_PRIVATE_KEY }}
      ADJUST_PYPI_USERNAME: ${{ secrets.ADJUST_PYPI_USERNAME }}
      ADJUST_PYPI_PASSWORD: ${{ secrets.ADJUST_PYPI_PASSWORD }}
