name: Continuous Integration

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  continuous-integration:
    uses: adjust/githubWorkflows/.github/workflows/automatePackageCI.yml@v6.1.6
    secrets:
      SLACK_WEBHOOK_URL: ${{ secrets.AUTOMATE_SLACK_WEBHOOK }}
      GITHUB_ORGANIZATION_ACCESS_TOKEN: ${{ secrets.AUTOMATE_GITHUB_ACCESS_TOKEN }}
      PYPI_SSH_KEY: ${{ secrets.AUTOMATE_DEPLOY_SSH_KEY }}
      ADJUST_PYPI_USERNAME: ${{ secrets.ADJUST_PYPI_USERNAME }}
      ADJUST_PYPI_PASSWORD: ${{ secrets.ADJUST_PYPI_PASSWORD }}
